# Generated by Django 5.1.2 on 2024-10-22 22:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('peanuts', 'Peanuts'), ('treenuts', 'Tree Nuts'), ('dairy', 'Dairy'), ('egg', 'Egg'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('fish', 'Fish'), ('crustaceans_shellfish', 'Crustaceans/Shellfish'), ('sesame', 'Sesame'), ('mustard', 'Mustard'), ('celery', 'Celery'), ('molluscs', 'Molluscs'), ('meat', 'Meat'), ('gluten', 'Gluten'), ('fruit', 'Fruit'), ('vegetables', 'Vegetables')], max_length=123),
        ),
    ]
