# Generated by Django 5.1.2 on 2024-10-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_images/default_profile_pic.jpg', upload_to='profile_images/'),
        ),
    ]
